services:
  postgres:
    image: postgres:latest
    container_name: megebase_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - megebase_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: megebase_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - megebase_network
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: megebase_rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - megebase_network

  redis:
    image: redis:7.4.5-alpine
    container_name: megebase_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - megebase_network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  megebase-identity-service:
    build:
      context: ../megebase-identity-service
      dockerfile: Dockerfile
    container_name: megebase_identity_service
    ports:
      - "${MEGEBASE_IDENTITY_SERVICE_PORT}:8080"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    volumes:
      - ../megebase-identity-service/.env:/app/.env
    networks:
      - megebase_network

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
  redis_data:

networks:
  megebase_network:
    driver: bridge