services:
  postgres:
    image: postgres:latest
    container_name: megebase_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - megebase_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: megebase_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - megebase_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  megebase_network:
    driver: bridge